name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy main branch to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: hera.krystal.co.uk
          port: 722
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          
          script: |
            cd masjid-frontend
            git pull origin main
            git status